<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://tempuri.org/" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" name="WSTimbrado" targetNamespace="http://tempuri.org/">
  <wsp:Policy wsu:Id="BasicHttpsBinding_IWSTimbrado_policy">
    <wsp:ExactlyOne>
      <wsp:All>
        <sp:TransportBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
          <wsp:Policy>
            <sp:TransportToken>
              <wsp:Policy>
                <sp:HttpsToken RequireClientCertificate="false"/>
              </wsp:Policy>
            </sp:TransportToken>
            <sp:AlgorithmSuite>
              <wsp:Policy>
                <sp:Basic256/>
              </wsp:Policy>
            </sp:AlgorithmSuite>
            <sp:Layout>
              <wsp:Policy>
                <sp:Strict/>
              </wsp:Policy>
            </sp:Layout>
          </wsp:Policy>
        </sp:TransportBinding>
      </wsp:All>
    </wsp:ExactlyOne>
  </wsp:Policy>
  <wsdl:types>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
      <xs:import namespace="http://schemas.datacontract.org/2004/07/WCFWSTimbrado"/>
      <xs:element name="TimbrarObjeto">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q1="http://schemas.datacontract.org/2004/07/WCFWSTimbrado" minOccurs="0" name="parametrosEntradaWSTimbrado" nillable="true" type="q1:ParametrosEntradaWSTimbrado"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="TimbrarObjetoResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q2="http://schemas.datacontract.org/2004/07/WCFWSTimbrado" minOccurs="0" name="TimbrarObjetoResult" nillable="true" type="q2:ParametrosSalidaWSTimbrado"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="TimbrarParametros">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="Usuario" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="Contrasenia" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="XMLPreCFDI" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="XMLOpcionales" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="IdAddenda" type="xs:int"/>
            <xs:element minOccurs="0" name="NodoAddenda" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="IdLlaveUnico" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="UUIDSucursal" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="Mail" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="MailCC" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="MailCCO" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="TimbrarParametrosResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="TimbrarParametrosResult" type="xs:boolean"/>
            <xs:element minOccurs="0" name="XMLCFDI" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="FolioFiscal" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="RutaPDF" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="Validacion3B" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="Sugerencias3B" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="IdValidacion" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="MensajeValidacion" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="CancelarParametros">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="Usuario" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="Contrasenia" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="RFCEmisor" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="FolioFiscal" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="CancelarParametrosResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="CancelarParametrosResult" type="xs:boolean"/>
            <xs:element minOccurs="0" name="IdValidacion" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="MensajeValidacion" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="CancelarObjeto">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q3="http://schemas.datacontract.org/2004/07/WCFWSTimbrado" minOccurs="0" name="parametrosEntradaWSCancelacion" nillable="true" type="q3:ParametrosEntradaWSCancelacion"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="CancelarObjetoResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q4="http://schemas.datacontract.org/2004/07/WCFWSTimbrado" minOccurs="0" name="CancelarObjetoResult" nillable="true" type="q4:ParametrosSalidaWSCancelacion"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="RecuperaCFDIObjeto">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q5="http://schemas.datacontract.org/2004/07/WCFWSTimbrado" minOccurs="0" name="parametrosEntradaRecuperacionCFDI" nillable="true" type="q5:ParametrosEntradaRecuperacionCFDI"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="RecuperaCFDIObjetoResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q6="http://schemas.datacontract.org/2004/07/WCFWSTimbrado" minOccurs="0" name="RecuperaCFDIObjetoResult" nillable="true" type="q6:ParametrosSalidaRecuperacionCFDI"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="RecuperaCFDIParametros">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="Usuario" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="Contrasenia" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="XMLPreCFDI" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="FolioFiscal" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="RecuperaCFDIParametrosResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="RecuperaCFDIParametrosResult" type="xs:boolean"/>
            <xs:element minOccurs="0" name="XMLCFDI" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="EstatusCFDI" type="xs:int"/>
            <xs:element minOccurs="0" name="IdValidacion" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="MensajeValidacion" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="RecuperaAcuseCancelacion">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q7="http://schemas.datacontract.org/2004/07/WCFWSTimbrado" minOccurs="0" name="parametrosEntradaRecuperacionAcuseCancelacion" nillable="true" type="q7:ParametrosEntradaRecuperacionAcuseCancelacion"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="RecuperaAcuseCancelacionResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q8="http://schemas.datacontract.org/2004/07/WCFWSTimbrado" minOccurs="0" name="RecuperaAcuseCancelacionResult" nillable="true" type="q8:ParametrosSalidaRecuperacionAcuseCancelacion"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ValidaRFCSAT">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="Usuario" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="Contrasenia" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="Rfc" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ValidaRFCSATResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element minOccurs="0" name="ValidaRFCSATResult" type="xs:boolean"/>
            <xs:element minOccurs="0" name="IdValidacion" nillable="true" type="xs:string"/>
            <xs:element minOccurs="0" name="MensajeValidacion" nillable="true" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ConciliacionCFDI">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q9="http://schemas.datacontract.org/2004/07/WCFWSTimbrado" minOccurs="0" name="parametrosEntradaConciliacion" nillable="true" type="q9:ParametrosEntradaConciliacion"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ConciliacionCFDIResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q10="http://schemas.datacontract.org/2004/07/WCFWSTimbrado" minOccurs="0" name="ConciliacionCFDIResult" nillable="true" type="q10:ParametrosSalidaConciliacion"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ValidaEstatusCFDI">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q11="http://schemas.datacontract.org/2004/07/WCFWSTimbrado" minOccurs="0" name="parametrosEntradaValidaEstatusCFDI" nillable="true" type="q11:ParametrosEntradaValidaEstatusCFDI"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="ValidaEstatusCFDIResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element xmlns:q12="http://schemas.datacontract.org/2004/07/WCFWSTimbrado" minOccurs="0" name="ValidaEstatusCFDIResult" nillable="true" type="q12:ParametrosSalidaValidaEstatusCFDI"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/">
      <xs:element name="anyType" nillable="true" type="xs:anyType"/>
      <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
      <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
      <xs:element name="boolean" nillable="true" type="xs:boolean"/>
      <xs:element name="byte" nillable="true" type="xs:byte"/>
      <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
      <xs:element name="decimal" nillable="true" type="xs:decimal"/>
      <xs:element name="double" nillable="true" type="xs:double"/>
      <xs:element name="float" nillable="true" type="xs:float"/>
      <xs:element name="int" nillable="true" type="xs:int"/>
      <xs:element name="long" nillable="true" type="xs:long"/>
      <xs:element name="QName" nillable="true" type="xs:QName"/>
      <xs:element name="short" nillable="true" type="xs:short"/>
      <xs:element name="string" nillable="true" type="xs:string"/>
      <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
      <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
      <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
      <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
      <xs:element name="char" nillable="true" type="tns:char"/>
      <xs:simpleType name="char">
        <xs:restriction base="xs:int"/>
      </xs:simpleType>
      <xs:element name="duration" nillable="true" type="tns:duration"/>
      <xs:simpleType name="duration">
        <xs:restriction base="xs:duration">
          <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
          <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
          <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:element name="guid" nillable="true" type="tns:guid"/>
      <xs:simpleType name="guid">
        <xs:restriction base="xs:string">
          <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
        </xs:restriction>
      </xs:simpleType>
      <xs:attribute name="FactoryType" type="xs:QName"/>
      <xs:attribute name="Id" type="xs:ID"/>
      <xs:attribute name="Ref" type="xs:IDREF"/>
    </xs:schema>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.datacontract.org/2004/07/WCFWSTimbrado" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/WCFWSTimbrado">
      <xs:complexType name="ParametrosEntradaWSTimbrado">
        <xs:sequence>
          <xs:element minOccurs="0" name="Contrasenia" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="IdAddenda" type="xs:int"/>
          <xs:element minOccurs="0" name="IdLlaveUnico" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="MailCC" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="MailCCO" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="MailPara" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="NodoAddenda" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="UUIDSucursal" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="Usuario" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="XMLOpcionales" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="XMLPreCFDI" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ParametrosEntradaWSTimbrado" nillable="true" type="tns:ParametrosEntradaWSTimbrado"/>
      <xs:complexType name="ParametrosSalidaWSTimbrado">
        <xs:sequence>
          <xs:element minOccurs="0" name="EstatusRespuesta" type="xs:boolean"/>
          <xs:element minOccurs="0" name="FolioFiscal" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="IdValidacion" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="MensajeValidacion" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="RutaPDF" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="Sugerencias3B" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="Validacion3B" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="XMLTimbrado" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ParametrosSalidaWSTimbrado" nillable="true" type="tns:ParametrosSalidaWSTimbrado"/>
      <xs:complexType name="ParametrosEntradaWSCancelacion">
        <xs:sequence>
          <xs:element minOccurs="0" name="Contrasenia" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="FolioFiscal" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="RFCEmisor" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="Usuario" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ParametrosEntradaWSCancelacion" nillable="true" type="tns:ParametrosEntradaWSCancelacion"/>
      <xs:complexType name="ParametrosSalidaWSCancelacion">
        <xs:sequence>
          <xs:element minOccurs="0" name="EstatusRespuesta" type="xs:boolean"/>
          <xs:element minOccurs="0" name="IdValidacion" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="MensajeValidacion" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ParametrosSalidaWSCancelacion" nillable="true" type="tns:ParametrosSalidaWSCancelacion"/>
      <xs:complexType name="ParametrosEntradaRecuperacionCFDI">
        <xs:sequence>
          <xs:element minOccurs="0" name="Contrasenia" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="FolioFiscal" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="Usuario" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="XMLPreCFDI" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ParametrosEntradaRecuperacionCFDI" nillable="true" type="tns:ParametrosEntradaRecuperacionCFDI"/>
      <xs:complexType name="ParametrosSalidaRecuperacionCFDI">
        <xs:sequence>
          <xs:element minOccurs="0" name="EstatusCFDI" type="xs:int"/>
          <xs:element minOccurs="0" name="EstatusRespuesta" type="xs:boolean"/>
          <xs:element minOccurs="0" name="IdValidacion" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="MensajeValidacion" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="XMLCFDI" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ParametrosSalidaRecuperacionCFDI" nillable="true" type="tns:ParametrosSalidaRecuperacionCFDI"/>
      <xs:complexType name="ParametrosEntradaRecuperacionAcuseCancelacion">
        <xs:sequence>
          <xs:element minOccurs="0" name="Contrasenia" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="FolioFiscal" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="RFCEmisor" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="Usuario" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ParametrosEntradaRecuperacionAcuseCancelacion" nillable="true" type="tns:ParametrosEntradaRecuperacionAcuseCancelacion"/>
      <xs:complexType name="ParametrosSalidaRecuperacionAcuseCancelacion">
        <xs:sequence>
          <xs:element minOccurs="0" name="AcuseCancelacion" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="EstatusRespuesta" type="xs:boolean"/>
          <xs:element minOccurs="0" name="IdValidacion" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="MensajeValidacion" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ParametrosSalidaRecuperacionAcuseCancelacion" nillable="true" type="tns:ParametrosSalidaRecuperacionAcuseCancelacion"/>
      <xs:complexType name="ParametrosEntradaConciliacion">
        <xs:sequence>
          <xs:element minOccurs="0" name="Contrasenia" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="FechaTimbrado" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="RFCEmisor" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="Usuario" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ParametrosEntradaConciliacion" nillable="true" type="tns:ParametrosEntradaConciliacion"/>
      <xs:complexType name="ParametrosSalidaConciliacion">
        <xs:sequence>
          <xs:element minOccurs="0" name="EstatusRespuesta" type="xs:boolean"/>
          <xs:element minOccurs="0" name="IdValidacion" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="MensajeValidacion" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="XmlConciliacion" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ParametrosSalidaConciliacion" nillable="true" type="tns:ParametrosSalidaConciliacion"/>
      <xs:complexType name="ParametrosEntradaValidaEstatusCFDI">
        <xs:sequence>
          <xs:element minOccurs="0" name="Contrasenia" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="FolioFiscal" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="RFCEmisor" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="Usuario" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ParametrosEntradaValidaEstatusCFDI" nillable="true" type="tns:ParametrosEntradaValidaEstatusCFDI"/>
      <xs:complexType name="ParametrosSalidaValidaEstatusCFDI">
        <xs:sequence>
          <xs:element minOccurs="0" name="EstatusCFDI" type="xs:int"/>
          <xs:element minOccurs="0" name="EstatusRespuesta" type="xs:boolean"/>
          <xs:element minOccurs="0" name="IdValidacion" nillable="true" type="xs:string"/>
          <xs:element minOccurs="0" name="MensajeValidacion" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
      <xs:element name="ParametrosSalidaValidaEstatusCFDI" nillable="true" type="tns:ParametrosSalidaValidaEstatusCFDI"/>
    </xs:schema>
  </wsdl:types>
  <wsdl:message name="IWSTimbrado_TimbrarObjeto_InputMessage">
    <wsdl:part name="parameters" element="tns:TimbrarObjeto"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_TimbrarObjeto_OutputMessage">
    <wsdl:part name="parameters" element="tns:TimbrarObjetoResponse"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_TimbrarParametros_InputMessage">
    <wsdl:part name="parameters" element="tns:TimbrarParametros"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_TimbrarParametros_OutputMessage">
    <wsdl:part name="parameters" element="tns:TimbrarParametrosResponse"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_CancelarParametros_InputMessage">
    <wsdl:part name="parameters" element="tns:CancelarParametros"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_CancelarParametros_OutputMessage">
    <wsdl:part name="parameters" element="tns:CancelarParametrosResponse"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_CancelarObjeto_InputMessage">
    <wsdl:part name="parameters" element="tns:CancelarObjeto"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_CancelarObjeto_OutputMessage">
    <wsdl:part name="parameters" element="tns:CancelarObjetoResponse"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_RecuperaCFDIObjeto_InputMessage">
    <wsdl:part name="parameters" element="tns:RecuperaCFDIObjeto"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_RecuperaCFDIObjeto_OutputMessage">
    <wsdl:part name="parameters" element="tns:RecuperaCFDIObjetoResponse"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_RecuperaCFDIParametros_InputMessage">
    <wsdl:part name="parameters" element="tns:RecuperaCFDIParametros"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_RecuperaCFDIParametros_OutputMessage">
    <wsdl:part name="parameters" element="tns:RecuperaCFDIParametrosResponse"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_RecuperaAcuseCancelacion_InputMessage">
    <wsdl:part name="parameters" element="tns:RecuperaAcuseCancelacion"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_RecuperaAcuseCancelacion_OutputMessage">
    <wsdl:part name="parameters" element="tns:RecuperaAcuseCancelacionResponse"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_ValidaRFCSAT_InputMessage">
    <wsdl:part name="parameters" element="tns:ValidaRFCSAT"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_ValidaRFCSAT_OutputMessage">
    <wsdl:part name="parameters" element="tns:ValidaRFCSATResponse"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_ConciliacionCFDI_InputMessage">
    <wsdl:part name="parameters" element="tns:ConciliacionCFDI"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_ConciliacionCFDI_OutputMessage">
    <wsdl:part name="parameters" element="tns:ConciliacionCFDIResponse"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_ValidaEstatusCFDI_InputMessage">
    <wsdl:part name="parameters" element="tns:ValidaEstatusCFDI"/>
  </wsdl:message>
  <wsdl:message name="IWSTimbrado_ValidaEstatusCFDI_OutputMessage">
    <wsdl:part name="parameters" element="tns:ValidaEstatusCFDIResponse"/>
  </wsdl:message>
  <wsdl:portType name="IWSTimbrado">
    <wsdl:operation name="TimbrarObjeto">
      <wsdl:input wsaw:Action="http://tempuri.org/IWSTimbrado/TimbrarObjeto" message="tns:IWSTimbrado_TimbrarObjeto_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IWSTimbrado/TimbrarObjetoResponse" message="tns:IWSTimbrado_TimbrarObjeto_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="TimbrarParametros">
      <wsdl:input wsaw:Action="http://tempuri.org/IWSTimbrado/TimbrarParametros" message="tns:IWSTimbrado_TimbrarParametros_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IWSTimbrado/TimbrarParametrosResponse" message="tns:IWSTimbrado_TimbrarParametros_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="CancelarParametros">
      <wsdl:input wsaw:Action="http://tempuri.org/IWSTimbrado/CancelarParametros" message="tns:IWSTimbrado_CancelarParametros_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IWSTimbrado/CancelarParametrosResponse" message="tns:IWSTimbrado_CancelarParametros_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="CancelarObjeto">
      <wsdl:input wsaw:Action="http://tempuri.org/IWSTimbrado/CancelarObjeto" message="tns:IWSTimbrado_CancelarObjeto_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IWSTimbrado/CancelarObjetoResponse" message="tns:IWSTimbrado_CancelarObjeto_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="RecuperaCFDIObjeto">
      <wsdl:input wsaw:Action="http://tempuri.org/IWSTimbrado/RecuperaCFDIObjeto" message="tns:IWSTimbrado_RecuperaCFDIObjeto_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IWSTimbrado/RecuperaCFDIObjetoResponse" message="tns:IWSTimbrado_RecuperaCFDIObjeto_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="RecuperaCFDIParametros">
      <wsdl:input wsaw:Action="http://tempuri.org/IWSTimbrado/RecuperaCFDIParametros" message="tns:IWSTimbrado_RecuperaCFDIParametros_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IWSTimbrado/RecuperaCFDIParametrosResponse" message="tns:IWSTimbrado_RecuperaCFDIParametros_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="RecuperaAcuseCancelacion">
      <wsdl:input wsaw:Action="http://tempuri.org/IWSTimbrado/RecuperaAcuseCancelacion" message="tns:IWSTimbrado_RecuperaAcuseCancelacion_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IWSTimbrado/RecuperaAcuseCancelacionResponse" message="tns:IWSTimbrado_RecuperaAcuseCancelacion_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="ValidaRFCSAT">
      <wsdl:input wsaw:Action="http://tempuri.org/IWSTimbrado/ValidaRFCSAT" message="tns:IWSTimbrado_ValidaRFCSAT_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IWSTimbrado/ValidaRFCSATResponse" message="tns:IWSTimbrado_ValidaRFCSAT_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="ConciliacionCFDI">
      <wsdl:input wsaw:Action="http://tempuri.org/IWSTimbrado/ConciliacionCFDI" message="tns:IWSTimbrado_ConciliacionCFDI_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IWSTimbrado/ConciliacionCFDIResponse" message="tns:IWSTimbrado_ConciliacionCFDI_OutputMessage"/>
    </wsdl:operation>
    <wsdl:operation name="ValidaEstatusCFDI">
      <wsdl:input wsaw:Action="http://tempuri.org/IWSTimbrado/ValidaEstatusCFDI" message="tns:IWSTimbrado_ValidaEstatusCFDI_InputMessage"/>
      <wsdl:output wsaw:Action="http://tempuri.org/IWSTimbrado/ValidaEstatusCFDIResponse" message="tns:IWSTimbrado_ValidaEstatusCFDI_OutputMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpsBinding_IWSTimbrado" type="tns:IWSTimbrado">
    <wsp:PolicyReference URI="#BasicHttpsBinding_IWSTimbrado_policy"/>
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="TimbrarObjeto">
      <soap:operation soapAction="http://tempuri.org/IWSTimbrado/TimbrarObjeto" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="TimbrarParametros">
      <soap:operation soapAction="http://tempuri.org/IWSTimbrado/TimbrarParametros" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CancelarParametros">
      <soap:operation soapAction="http://tempuri.org/IWSTimbrado/CancelarParametros" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CancelarObjeto">
      <soap:operation soapAction="http://tempuri.org/IWSTimbrado/CancelarObjeto" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RecuperaCFDIObjeto">
      <soap:operation soapAction="http://tempuri.org/IWSTimbrado/RecuperaCFDIObjeto" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RecuperaCFDIParametros">
      <soap:operation soapAction="http://tempuri.org/IWSTimbrado/RecuperaCFDIParametros" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="RecuperaAcuseCancelacion">
      <soap:operation soapAction="http://tempuri.org/IWSTimbrado/RecuperaAcuseCancelacion" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ValidaRFCSAT">
      <soap:operation soapAction="http://tempuri.org/IWSTimbrado/ValidaRFCSAT" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ConciliacionCFDI">
      <soap:operation soapAction="http://tempuri.org/IWSTimbrado/ConciliacionCFDI" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ValidaEstatusCFDI">
      <soap:operation soapAction="http://tempuri.org/IWSTimbrado/ValidaEstatusCFDI" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="WSTimbrado">
    <wsdl:port name="BasicHttpsBinding_IWSTimbrado" binding="tns:BasicHttpsBinding_IWSTimbrado">
      <soap:address location="https://wstimbradopruebas.facturaxion.com/WSTimbrado.svc"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
